#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

chain_id: chain1    # 链标识
version: v1.0.0         # 链版本
sequence: 1             # 配置版本
auth_type: "identity"   # 认证类型

crypto:
  hash: SHA256

# 交易、区块相关配置
block:
  tx_timestamp_verify: true # 是否需要开启交易时间戳校验
  tx_timeout: 600  # 交易时间戳的过期时间(秒)
  block_tx_capacity: 100  # 区块中最大交易数
  block_size: 10  # 区块最大限制，单位MB
  block_interval: 2000 # 出块间隔，单位:ms

# core模块
core:
  tx_scheduler_timeout: 10 #  [0, 60] 交易调度器从交易池拿到交易后, 进行调度的时间
  tx_scheduler_validate_timeout: 10 # [0, 60] 交易调度器从区块中拿到交易后, 进行验证的超时时间

#共识配置
consensus:
  # 共识类型(0-SOLO,1-TBFT,2-MBFT,3-HOTSTUFF,4-RAFT,10-POW)
  type: 1
  # 共识节点列表，组织必须出现在trust_roots的org_id中，每个组织可配置多个共识节点，节点地址采用libp2p格式
  nodes:
    - org_id: "wx-org1.chainmaker.org"
      address:
        - "/ip4/10.190.28.222/tcp/11301/p2p/QmeXXfQgh3yAyA7gvHut3fR96GTucZZsTg92SC64WnV2WX"
    - org_id: "wx-org2.chainmaker.org"
      address:
        - "/ip4/10.190.28.222/tcp/11302/p2p/QmfBAtFNRdiFSGM6mLU1eir7TUA2YtQT5sxBLdWKeZ9vCY"
    - org_id: "wx-org3.chainmaker.org"
      address:
        - "/ip4/10.190.28.222/tcp/11303/p2p/QmX12zQJgWjtKuwZbLgi1Ub6udYKBqWonQZz9uKzaDyTY5"
    - org_id: "wx-org4.chainmaker.org"
      address:
        - "/ip4/10.190.28.222/tcp/11304/p2p/QmWSCTAnJz3mgz6WVWUknFFVpNmQmGGupwBDYii4adUn56"
  #    - org_id: "wx-org5.chainmaker.org"
  #      address:
  #        - "/ip4/10.190.28.222/tcp/11305/p2p/Qmdixv2PbNxoxSakgPKdbikbHtiFYTwELP2p3EESMCdrCR"
  #    - org_id: "wx-org6.chainmaker.org"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/11306/p2p/QmY4fH1dp22z26Fon2NhEU7oRn358vhnhE3hLTep4ntY1Q"
  #    - org_id: "wx-org7.chainmaker.org"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/11307/p2p/QmQ9454HST8hYpnQ4czqNFHpEsqBdJRK3GcB9d8w1aJEqR"
  #    - org_id: "wx-org8.chainmaker.org"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/11308/p2p/QmNLvF3TkBcenPwjzEtJoEUGbCXmvUvqi3uR9T5fVBB8VG"
  #    - org_id: "wx-org9.chainmaker.org"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/11309/p2p/Qmf3dekGL7GPKD9frQHcoFpwrFiRPTV68BBi9pQWsaN8BT"
  #    - org_id: "wx-org10.chainmaker.org"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/11310/p2p/QmaHZvX4t14jzmoVAa9wVHsb18w5oMYSu8vrgn1fdGPYgc"
  #    - org_id: "{org11_id}"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/{org11_port}/p2p/{org11_peerid}"
  #    - org_id: "{org12_id}"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/{org12_port}/p2p/{org12_peerid}"
  #    - org_id: "{org13_id}"
  #      address:
  #        - "/ip4/127.0.0.1/tcp/{org13_port}/p2p/{org13_peerid}"
  ext_config: # 扩展字段，记录难度、奖励等其他类共识算法配置
    - key: aa
      value: chain01_ext11

# 信任组织和根证书
trust_roots:
  - org_id: "wx-org1.chainmaker.org"
    root: "./certs/ca/wx-org1.chainmaker.org/ca.crt"
  - org_id: "wx-org2.chainmaker.org"
    root: "./certs/ca/wx-org2.chainmaker.org/ca.crt"
  - org_id: "wx-org3.chainmaker.org"
    root: "./certs/ca/wx-org3.chainmaker.org/ca.crt"
  - org_id: "wx-org4.chainmaker.org"
    root: "./certs/ca/wx-org4.chainmaker.org/ca.crt"
#  - org_id: "wx-org5.chainmaker.org"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/wx-org5.chainmaker.org/ca.crt"
#  - org_id: "wx-org6.chainmaker.org"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/wx-org6.chainmaker.org/ca.crt"
#  - org_id: "wx-org7.chainmaker.org"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/wx-org7.chainmaker.org/ca.crt"
#  - org_id: "wx-org8.chainmaker.org"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/wx-org8.chainmaker.org/ca.crt"
#  - org_id: "wx-org9.chainmaker.org"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/wx-org9.chainmaker.org/ca.crt"
#  - org_id: "wx-org10.chainmaker.org"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/wx-org10.chainmaker.org/ca.crt"
#  - org_id: "{org11_id}"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/{org11_id}/ca.crt"
#  - org_id: "{org12_id}"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/{org12_id}/ca.crt"
#  - org_id: "{org13_id}"
#    root: "../config/wx-org1.chainmaker.org/certs/ca/{org13_id}/ca.crt"

# 权限配置（只能整体添加、修改、删除）
resource_policies:
  - resource_name: NODE_ADDR_UPDATE
    policy:
      rule: SELF # 规则（ANY，MAJORITY...，全部大写，自动转大写）
      org_list: # 组织名称（组织名称，区分大小写）
      role_list: # 角色名称（role，自动转大写）
        - admin
  - resource_name: TRUST_ROOT_UPDATE
    policy:
      rule: SELF # 规则（ANY，MAJORITY...，全部大写）
      org_list: # 组织名称（组织名称）
      role_list: # 角色名称（role，自动转大写）
        - admin
  - resource_name: CONSENSUS_EXT_DELETE
    policy:
      rule: MAJORITY
      org_list:
      role_list:
        - admin
  - resource_name: BLOCK_UPDATE
    policy:
      rule: ANY
      org_list:
      role_list:
        - admin
        - client
  - resource_name: INIT_CONTRACT
    policy:
      rule: ANY
      org_list:
      role_list:
  - resource_name: UPGRADE_CONTRACT
    policy:
      rule: ANY
      org_list:
      role_list:
  - resource_name: FREEZE_CONTRACT
    policy:
      rule: ANY
      org_list:
      role_list:
  - resource_name: UNFREEZE_CONTRACT
    policy:
      rule: ANY
      org_list:
      role_list:
  - resource_name: REVOKE_CONTRACT
    policy:
      rule: ANY
      org_list:
      role_list:
